# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kostas/Desktop/AiBToS-Project2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kostas/Desktop/AiBToS-Project2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostas/Desktop/AiBToS-Project2/CMakeFiles /home/kostas/Desktop/AiBToS-Project2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostas/Desktop/AiBToS-Project2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AiBToS_Project2

# Build rule for target.
AiBToS_Project2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AiBToS_Project2
.PHONY : AiBToS_Project2

# fast build rule for target.
AiBToS_Project2/fast:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/build
.PHONY : AiBToS_Project2/fast

src/Naive.o: src/Naive.cpp.o
.PHONY : src/Naive.o

# target to build an object file
src/Naive.cpp.o:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/src/Naive.cpp.o
.PHONY : src/Naive.cpp.o

src/Naive.i: src/Naive.cpp.i
.PHONY : src/Naive.i

# target to preprocess a source file
src/Naive.cpp.i:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/src/Naive.cpp.i
.PHONY : src/Naive.cpp.i

src/Naive.s: src/Naive.cpp.s
.PHONY : src/Naive.s

# target to generate assembly for a file
src/Naive.cpp.s:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/src/Naive.cpp.s
.PHONY : src/Naive.cpp.s

src/Program.o: src/Program.cpp.o
.PHONY : src/Program.o

# target to build an object file
src/Program.cpp.o:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/src/Program.cpp.o
.PHONY : src/Program.cpp.o

src/Program.i: src/Program.cpp.i
.PHONY : src/Program.i

# target to preprocess a source file
src/Program.cpp.i:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/src/Program.cpp.i
.PHONY : src/Program.cpp.i

src/Program.s: src/Program.cpp.s
.PHONY : src/Program.s

# target to generate assembly for a file
src/Program.cpp.s:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/src/Program.cpp.s
.PHONY : src/Program.cpp.s

src/SimpleParser.o: src/SimpleParser.cpp.o
.PHONY : src/SimpleParser.o

# target to build an object file
src/SimpleParser.cpp.o:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/src/SimpleParser.cpp.o
.PHONY : src/SimpleParser.cpp.o

src/SimpleParser.i: src/SimpleParser.cpp.i
.PHONY : src/SimpleParser.i

# target to preprocess a source file
src/SimpleParser.cpp.i:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/src/SimpleParser.cpp.i
.PHONY : src/SimpleParser.cpp.i

src/SimpleParser.s: src/SimpleParser.cpp.s
.PHONY : src/SimpleParser.s

# target to generate assembly for a file
src/SimpleParser.cpp.s:
	$(MAKE) -f CMakeFiles/AiBToS_Project2.dir/build.make CMakeFiles/AiBToS_Project2.dir/src/SimpleParser.cpp.s
.PHONY : src/SimpleParser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... AiBToS_Project2"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Naive.o"
	@echo "... src/Naive.i"
	@echo "... src/Naive.s"
	@echo "... src/Program.o"
	@echo "... src/Program.i"
	@echo "... src/Program.s"
	@echo "... src/SimpleParser.o"
	@echo "... src/SimpleParser.i"
	@echo "... src/SimpleParser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

